name: Run Playwright Tests

on:
  push:
    branches: [ "main" ]

jobs:
  app:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Start Demo App (Dev Server)
        run: npm run dev & 

      - name: Waiting Demo app starting
        run: |
          npx wait-on http://localhost:3000 -t 120000
          echo "Demo App ready"

      - name: Install Playwright with browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          BASE_URL: http://localhost:3000
          EMAIL: ${{secrets.EMAIL}}
          PASSWORD: ${{secrets.PASSWORD}}